### ISSUE TITLE
hi,can we develop this project together?

### ISSUE THREAD

**Issue by zky001** [mfreeborn/fastapi-sqlalchemy#12]
I write a Saas platform using the fastapi  and  SQLAlchemy，
In past 5 years，I use Flask_SQLAlchemy and read it's source code   many times  Now I want to do something for fastapi

**Comment by mfreeborn** [comment]
Hi, thanks for your interest. I'd be very happy to accept pull requests for any features you think would be useful. At the moment, I realise that this library is quite a thin wrapper over sqlalchemy just to reduce boilerplate when integrating with Starlette/FastAPI apps.
