### ISSUE TITLE
How to use this package with pytest? 

### ISSUE THREAD

**Issue by ahmednafies** [mfreeborn/fastapi-sqlalchemy#3]
I wonder how to use this package with pytest. to setup a test database and tear down after test is completed

**Comment by mfreeborn** [comment]
Interesting question. I think one very possible option would be to test using an sqlite in-memory database. With pytest, create a fixture for your app which uses scope=function,  then, each new test will have a fresh database.

**Comment by ahmednafies** [comment]
Thank you, I will try it out

**Comment by mfreeborn** [comment]
Good luck, I'll close this for now but happy for it to be re-opened if necessary. It would be great to see your implementation once finished.
