### ISSUE TITLE
Routing does not need to be connected database through dependency injection ？

### ISSUE THREAD

**Issue by Jieszs** [mfreeborn/fastapi-sqlalchemy#39]
`@router.get("/metaEvents/{event_id}")
async def get_one(
        event_id: int,
        db: Session = Depends(deps.get_db),
):`

**Comment by Jieszs** [comment]
How to make sure the database session is always closed after the request. Even if there was an exception while processing the request.

**Comment by Ewen-Zippedscript** [comment]
Fixed in #49
