### ISSUE TITLE
If I have two or more databases that need to be connected, how should I use them?

### ISSUE THREAD

**Issue by xhatt** [mfreeborn/fastapi-sqlalchemy#48]
## First of all, thank you for opening up the middleware. I have a question. If I have two or more databases that need to be connected, how should I use them?

**Comment by hadrien** [comment]
I had the same issue and switched to [FastAPI-SQLA](https://github.com/dialoguemd/fastapi-sqla) which allows configuring several DBs -> https://github.com/dialoguemd/fastapi-sqla/#multi-session-support

**Comment by xhatt** [comment]
> I had the same issue and switched to [FastAPI-SQLA](https://github.com/dialoguemd/fastapi-sqla) which allows configuring several DBs -> https://github.com/dialoguemd/fastapi-sqla/#multi-session-support

Okay, thank you very much, even though I don't need this yet
